---
title: "AUC"
author: "Arnab Aich"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,comment=NA, message=FALSE, warning=FALSE)

library(tidyverse)
library(rio)
library(openxlsx)
library(ggplot2)
library(mice)
library(gridExtra)
library(readr)
library(patchwork)
```

```{r}
# Define the number of ids, visits, and time points
num_ids <- 200
panel_data <- expand.grid(
  id = 1:num_ids,
  visit = c("a", "b", "c", "d", "e"),
  time = c("1","2","3","4","5","6","7","8")
)

# Assign a random treatment (0 or 1) to each id
treatment<- data.frame(id =  1:num_ids, treatment = sample(0:1, num_ids, replace = TRUE))
# Merge the treatment information into the panel dataset
panel_data <- merge(panel_data, treatment, by = "id")
```

```{r}
panel_data <- panel_data %>%
  mutate(
    measurement = case_when(
      treatment == 1 ~ case_when(
        visit == "a" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 3+((4-1)/2)**2, sd = 1),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 3+((4-2)/2)**2, sd = 1),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 3+((4-3)/2)**2, sd = 1),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 3+((4-4)/2)**2, sd = 1),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 3+((4-5)/2)**2, sd = 1),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 3+((4-6)/2)**2, sd = 1),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 3+((4-7)/2)**2, sd = 1),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 3+((4-8)/2)**2, sd = 1)
        ),
        visit == "b" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 5+((4-1)/2)**2, sd = 1),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 5+((4-2)/2)**2, sd = 1),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 5+((4-3)/2)**2, sd = 1),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 5+((4-4)/2)**2, sd = 1),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 5+((4-5)/2)**2, sd = 1),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 5+((4-6)/2)**2, sd = 1),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 5+((4-7)/2)**2, sd = 1),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 5+((4-8)/2)**2, sd = 1)
        ),
        visit == "c" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-1)/2)**2, sd = 1),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-2)/2)**2, sd = 1),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-3)/2)**2, sd = 1),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-4)/2)**2, sd = 1),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-5)/2)**2, sd = 1),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-6)/2)**2, sd = 1),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-7)/2)**2, sd = 1),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 6.5+((4-8)/2)**2, sd = 1)
        ),
        visit == "d" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 8+((4-1)/2)**2, sd = 1),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 8+((4-2)/2)**2, sd = 1),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 8+((4-3)/2)**2, sd = 1),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 8+((4-4)/2)**2, sd = 1),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 8+((4-5)/2)**2, sd = 1),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 8+((4-6)/2)**2, sd = 1),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 8+((4-7)/2)**2, sd = 1),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 8+((4-8)/2)**2, sd = 1)
        ),
        visit == "e" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 10+((4-1)/2)**2, sd = 1),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 10+((4-2)/2)**2, sd = 1),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 10+((4-3)/2)**2, sd = 1),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 10+((4-4)/2)**2, sd = 1),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 10+((4-5)/2)**2, sd = 1),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 10+((4-6)/2)**2, sd = 1),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 10+((4-7)/2)**2, sd = 1),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 10+((4-8)/2)**2, sd = 1)
        )),
     treatment == 0 ~ case_when(
        visit == "a" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-1)/2)**2, sd = 0.75),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-2)/2)**2, sd = 0.75),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-3)/2)**2, sd = 0.75),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-4)/2)**2, sd = 0.75),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-5)/2)**2, sd = 0.75),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-6)/2)**2, sd = 0.75),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-7)/2)**2, sd = 0.75),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 2-3-((4-8)/2)**2, sd = 0.75)
        ),
        visit == "b" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-1)/2)**2, sd = 0.75),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-2)/2)**2, sd = 0.75),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-3)/2)**2, sd = 0.75),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-4)/2)**2, sd = 0.75),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-5)/2)**2, sd = 0.75),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-6)/2)**2, sd = 0.75),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-7)/2)**2, sd = 0.75),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 3-5-((4-8)/2)**2, sd = 0.75)
        ),
        visit == "c" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-1)/2)**2, sd = 0.75),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-2)/2)**2, sd = 0.75),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-3)/2)**2, sd = 0.75),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-4)/2)**2, sd = 0.75),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-5)/2)**2, sd = 0.75),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-6)/2)**2, sd = 0.75),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-7)/2)**2, sd = 0.75),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 4.5-6.5-((4-8)/2)**2, sd = 0.75)
        ),
        visit == "d" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-1)/2)**2, sd = 0.75),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-2)/2)**2, sd = 0.75),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-3)/2)**2, sd = 0.75),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-4)/2)**2, sd = 0.75),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-5)/2)**2, sd = 0.75),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-6)/2)**2, sd = 0.75),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-7)/2)**2, sd = 0.75),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 6-8-((4-8)/2)**2, sd = 0.75)
        ),
        visit == "e" ~ case_when(
          time == "1" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-1)/2)**2, sd = 0.75),
          time == "2" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-2)/2)**2, sd = 0.75),
          time == "3" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-3)/2)**2, sd = 0.75),
          time == "4" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-4)/2)**2, sd = 0.75),
          time == "5" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-5)/2)**2, sd = 0.75),
          time == "6" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-6)/2)**2, sd = 0.75),
          time == "7" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-7)/2)**2, sd = 0.75),
          time == "8" ~ rnorm(n = nrow(panel_data), mean = 7-10-((4-8)/2)**2, sd = 0.75)
        ))
    )
  )
head(panel_data)

```

# Trapezoidal AUC

```{r}
# Function to calculate AUC using the trapezoidal rule
trapezoidal_auc <- function(time, value) {
  n <- length(time)
  auc <- 0
  for (i in 1:(n-1)) {
    auc <- auc + (time[i+1] - time[i]) * (value[i+1] + value[i]) / 2
  }
  return(abs(auc))
}

# Calculate AUC for each individual id at each visit using the trapezoidal rule
auc_trapezoidal<- panel_data %>%
  group_by(id,visit) %>%
  summarise(auc = trapezoidal_auc(as.numeric(time), measurement))%>%
  ungroup()
print(auc_trapezoidal)


 # make an interaction plot of the AUC values for each id at each visit
p1 = ggplot(auc_trapezoidal, aes(x = visit, y = auc, group = id)) +
  geom_line(aes(color = id), alpha = 0.5) +
  geom_point(aes(color = id)) +
  labs(title = "AUC values for each id at each visit(Trapezoidal Rule)",
       x = "Visit",
       y = "AUC") +
  theme_minimal()
```

```{r}
auc_trapezoidal$treatment <- panel_data$treatment[match(auc_trapezoidal$id, panel_data$id)]
auc_trapezoidal$treatment <- factor(auc_trapezoidal$treatment, levels = c(0, 1), labels = c("Control", "Treatment"))
 # add an interaction plot of visit and auc averaging over id for two different treatment
p2=auc_trapezoidal %>%
  group_by(visit,treatment) %>%
  summarise(mean_auc = mean(auc)) %>%
  ggplot(aes(x = visit, y = mean_auc, group = treatment)) +
  geom_line(aes(color = treatment), alpha = 1.5) +
  geom_point(aes(color = treatment), alpha = 1.5) +
  labs(title = "AUC values for each visit averaged over id(Trapezoidal Rule)",
       x = "Visit",
       y = "Mean AUC") +
  theme_classic()
```

# adding 15% missing values

```{r adding 15% missing values, message=FALSE, warning=FALSE}
panel_data_missing <- panel_data %>%
  group_by(id) %>%
  mutate(missing = rbinom(n = n(), size = 1, prob = 0.15)) %>%
  ungroup() %>%
  mutate(measurement = ifelse(missing == 1, NA, measurement))
```

# imputing missing values
```{r message=FALSE, warning=FALSE, include=FALSE}
panel_data_mice <- complete(mice(panel_data_missing, m = 5, maxit = 50, method = "pmm"))
```


```{r}
# Calculate AUC for each individual id at each visit using the trapezoidal rule
auc_trapezoidal_mice<- panel_data_mice %>%
  group_by(id,visit) %>%
  summarise(auc = trapezoidal_auc(as.numeric(time), measurement))%>%
  ungroup()
print(auc_trapezoidal_mice)


 # make an interaction plot of the AUC values for each id at each visit
p3 = ggplot(auc_trapezoidal_mice, aes(x = visit, y = auc, group = id)) +
  geom_line(aes(color = id), alpha = 0.5) +
  geom_point(aes(color = id)) +
  labs(title = "AUC values for each id at each visit(Trapezoidal Rule)",
       x = "Visit",
       y = "AUC") +
  theme_minimal()
```

```{r}
auc_trapezoidal_mice$treatment <- panel_data_mice$treatment[match(auc_trapezoidal_mice$id, panel_data_mice$id)]
auc_trapezoidal_mice$treatment <- factor(auc_trapezoidal_mice$treatment, levels = c(0, 1), labels = c("Control", "Treatment"))
 # add an interaction plot of visit and auc averaging over id for two different treatment
p4=auc_trapezoidal_mice %>%
  group_by(visit,treatment) %>%
  summarise(mean_auc = mean(auc)) %>%
  ggplot(aes(x = visit, y = mean_auc, group = treatment)) +
  geom_line(aes(color = treatment), alpha = 1.5) +
  geom_point(aes(color = treatment), alpha = 1.5) +
  labs(title = "AUC values for each visit averaged over id(Trapezoidal Rule)",
       x = "Visit",
       y = "Mean AUC") +
  theme_classic()
```

```{r}
(p1+p2)/
(p3+p4)
```








































































