---
title: "Auc Cpeptide"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r}
library(readr)
library(xlsx)
library(tidyverse)
library(tidyverse)
library(rio)
library(openxlsx)
library(ggplot2)
library(mice)
library(gridExtra)
library(readr)
library(patchwork)
data<- read_csv("data/data_cpep.csv")
as.numeric(as.factor(data_mice$time))
```
# Trapezoidal AUC

```{r}
# Function to calculate AUC using the trapezoidal rule
trapezoidal_auc <- function(time, value) {
  n <- length(time)
  auc <- 0
  for (i in 1:(n-1)) {
    auc <- auc + (time[i+1] - time[i]) * (value[i+1] + value[i]) / 2
  }
  return(abs(auc))
}

data_mice <- complete(mice(data, m = 5, maxit = 50, method = "pmm"))
# Calculate AUC for each individual id at each visit using the trapezoidal rule
auc_cpep <- data_mice %>%
  group_by(subject, visit) %>%
  summarise(auc = trapezoidal_auc(as.numeric(as.factor(time)), result)) %>%
  ungroup()
write.xlsx(auc_auc_cpep, "data/auc_cpep.xlsx")
```

```{r}
data<- read_csv("data/data_gluc.csv")
data_mice <- complete(mice(data, m = 5, maxit = 50, method = "pmm"))
# Calculate AUC for each individual id at each visit using the trapezoidal rule
auc_glucose <- data_mice %>%
  group_by(subject, visit) %>%
  summarise(auc = trapezoidal_auc(as.numeric(as.factor(time)), result)) %>%
  ungroup()
write.xlsx(auc_glucose, "data/auc_gluc.xlsx")
```

# calculating Cpeptide index

```{r}
#divide cpep auc by glucose auc for each comnination of subject and visit and make a new dataset
data_cpep_auc<-read.xlsx("data/auc_cpep.xlsx")
data_gluc_auc<-read.xlsx("data/auc_gluc.xlsx")
data_auc<-merge(data_cpep_auc,data_gluc_auc,by=c("subject","visit"))
data_auc$index<-(data_auc$auc.x/data_auc$auc.y)*100
write.xlsx(data_auc,"data/cpep_index.xlsx")
# plot Cpeptide index by categorties
```

# C-Peptide index plot
```{r}
# Summarize the data to get mean for each visit
data_summary <- data_auc %>%
  group_by(visit) %>%
  summarize(mean_response = mean(index, na.rm = TRUE))

# Plot the summarized data
ggplot(data_summary, aes(x = visit, y = mean_response)) +
  geom_point(size = 1.5) +
  geom_line(aes(group = 1), size = 0.5) +
  labs(x = "Visit",
       y = "mean C-peptide index") +
  theme_classic()









```








