---
title: "Imputation Comparison"
author: "Arnab Aich"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE,comment=NA}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rio)
library(openxlsx)
library(ggplot2)
library(mice)
library(gridExtra)
library(readr)
```
# cpeptide
```{r}
data_cpep <- read_csv("data/data_cpep.csv")
# Identify rows with any missing values across all columns
missing_records <- data_cpep %>%
  filter(rowSums(is.na(.)) > 0)
sub = row.names(as.matrix(which(table(missing_records$subject)>=10)));sub
which(table(missing_records$subject)>1)
```

```{r}
data_cpep_miss <- data_cpep %>% filter(subject %in% sub)
data_cpep_mice = read.csv("data/data_cpep_mice.csv")
data_cpep_mice<- data_cpep_mice %>% filter(subject %in% sub)
```

```{r}
grid.arrange(
  ggplot(data_cpep_miss, aes(x = time, y = result , color = subject, group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()
,
  ggplot(data_cpep_miss, aes(x = visit, y = result , color = subject, group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "visit",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()
  ,
    ggplot(data_cpep_mice, aes(x = time, y = result , color = subject,group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()
,
  ggplot(data_cpep_mice, aes(x = visit, y = result , color = subject,group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()

  ,ncol = 2)
```

# glucose
```{r}
data_gluc <- read_csv("data/data_gluc.csv")
# Identify rows with any missing values across all columns
missing_records <- data_gluc %>%
  filter(rowSums(is.na(.)) > 0)
sub = row.names(as.matrix(which(table(missing_records$subject)>=1)));sub
which(table(missing_records$subject)<10)
```
```{r}
data_gluc_miss <- data_gluc %>% filter(subject %in% sub)
data_gluc_mice = read.csv("data/data_gluc_mice.csv")
data_gluc_mice<- data_gluc_mice %>% filter(subject %in% sub)
```
```{r}
grid.arrange(
  ggplot(data_gluc_miss, aes(x = time, y = result , color = subject,group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()
  ,
  ggplot(data_gluc_miss, aes(x = visit, y = result , color = subject,group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "visit",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()
  ,
    ggplot(data_gluc_mice, aes(x = time, y = result , color = subject,group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()
  ,
  ggplot(data_gluc_mice, aes(x = visit, y = result , color = subject,group = subject)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Subject")+
  theme_classic()
  ,ncol = 2)
```






