---
title: "OGTT-RMD"
author: "Arnab Aich"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, echo=FALSE }
knitr::opts_chunk$set(echo = FALSE,comment = NA)
library(tidyverse)
library(rio)
library(openxlsx)
library(ggplot2)
library(mice)
library(gridExtra)
library(readr)
```

```{r Get cohorts}
cohort <- import("data/Subject IDs by MAD cohort 2024-05-23.xlsx")
```

```{r First dose datetime, take baseline labs as last value prior to first dose}
#names(ex_edc); unique(ds_edc$`Cohort: (display value) (COHORT_DEC)`)
ex_edc <- import("data/ex.xlsx") |>
  filter(str_detect(`Visit Name (VISNAME)`,"Day 1")) |>
  filter(!str_detect(`Visit Name (VISNAME)`,"Day 14")) |> 
  filter(`Was dose taken? (EXYN)` == "Y") |>
  left_join(cohort, by=c("Subject Identifier (SUBNUM)"="Subject ID Assigned")) |>
  select(-c(`Site Number (SITENUM)`, `Internal Subject Id (SUBID)`,`Visit Id (VISITID)`:`Page Not Done (EXND)`,
            `Was dose taken? (display value) (EXYN_DEC)`,
            `If No, reason missed: (EXREASND)`:`Marked Deleted (DELETED)`)) |>
  unique() |>
  arrange(`Strata Group`, `Subject Identifier (SUBNUM)`) |>
  mutate(doublet_ind = case_when(
    `Subject Identifier (SUBNUM)` == lag(`Subject Identifier (SUBNUM)`) ~ 1,
    TRUE ~ 0
  )) |>
  filter(doublet_ind == 0) |>
  select(`Subject Identifier (SUBNUM)`, `Date: (EXSTDAT)`, `Time: (EXSTTIM)`)

# names(ex_edc_db2); unique(ds_edc$`Cohort: (display value) (COHORT_DEC)`)
ex_edc_db2 <- import("data/ex DB2.xlsx") |>
  filter(str_detect(`Visit Name (VISNAME)`,"Day 1")) |>
  filter(!str_detect(`Visit Name (VISNAME)`,"Day 14")) |> 
  filter(`Was dose taken? (EXYN)` == "Y")|>
  select(`Subject Identifier (SUBNUM)`, `Date: (EXSTDAT)`, `Time: (EXSTTIM)`)

first_dose <- bind_rows(ex_edc, ex_edc_db2) |>
  right_join(cohort, by=c("Subject Identifier (SUBNUM)"="Subject ID Assigned"))
```

```{r OGTT start times}

OGTT_times_db1 <- import("data/ag.xlsx") |>
  inner_join(cohort, by=c("Subject Identifier (SUBNUM)"="Subject ID Assigned")) |>
  select(`Subject Identifier (SUBNUM)`,
         `Visit Name (VISNAME)`,
         `OGTT Procedure Date: (AGSTDAT)`,
         `Glucose Consumption Start Time: (AGSTTIM)`) |>
  filter(!is.na(`Glucose Consumption Start Time: (AGSTTIM)`)) |>
  mutate(Visit = ifelse(str_detect(`Visit Name (VISNAME)`, "4 \\(M"), "Day 14", `Visit Name (VISNAME)`)) 

OGTT_times_db2 <- import("data/ag DB2.xlsx") |>
  inner_join(cohort, by=c("Subject Identifier (SUBNUM)"="Subject ID Assigned")) |>
  select(`Subject Identifier (SUBNUM)`,
         `Visit Name (VISNAME)`,
         `OGTT Procedure Date: (AGSTDAT)`,
         `Glucose Consumption Start Time: (AGSTTIM)`) |>
  filter(!is.na(`Glucose Consumption Start Time: (AGSTTIM)`)) |>
  mutate(Visit = ifelse(str_detect(`Visit Name (VISNAME)`, "4 \\(M"), "Day 14", `Visit Name (VISNAME)`)) 

OGTT_times <- bind_rows(OGTT_times_db1, OGTT_times_db2) |>
  select(-`Visit Name (VISNAME)`)

 # rm(OGTT_times_db1, OGTT_times_db2)
```

```{r PPD CL data}
PPD_lb_tnsf_gluc_insulin <- import("data/glucose insulin cpeptide all MAD cohorts 2024-05-23.xlsx") |>
  rename(`Subject level ID or Number (SUBJID)`=`Subject ID or Number (SUBJID)`,
         `lab date (lbdt)`=`LBDT (LBDT)`,
         `lab time (lbtm)`=`LBTM (LBTM)`,
         `Received Date (RCVDTM)`=`Received Date and Time (RCVDTM)`) |>
  select(`Study ID or Number (STUDYID)`,
         `Subject level ID or Number (SUBJID)`,
         `Subject Sex (SEX)`,
         `Subject Age at Collection (AGEATCOL)`,
         `Subject Race (RACE)`,
         `Visit Name (VISIT)`,
         `Accession ID or Number (ACCSNNUM)`,
         `Specimen ID or Number (SPECNUM)`,
         `lab date (lbdt)`,
         `lab time (lbtm)`,
         `Received Date (RCVDTM)`,
         `Specimen Condition (SPECCND)`,
         `Lab - Specimen Comments (SPECCOM)`,
         `Specimen Material Name (LBSPEC)`,
         `Fasting Status (FASTSTAT)`,
         `Battery ID (BATTRID)`,
         `Lab Test ID (LBTESTCD)`,
         `Lab Test Name (LBTEST)`,
         `Test ID (TSTCD)`,
         `Test Name ID (TSTNAM)`:`Transaction Type (TRNSTYP)`
  ) |>
  mutate(`lab date` = ymd(`lab date (lbdt)`)) 

# unique(PPD_lb_tnsf_gluc_insulin$`Lab Test Name (LBTEST)`)
```

```{r Begin Cpeptide work filter PPD CL to cpeptide, include=FALSE}
PPD_lb_tnsf_cpeptide <- PPD_lb_tnsf_gluc_insulin |> # names(PPD_lb_tnsf_gluc_insulin)
  filter(`Lab Test Name (LBTEST)` == "C Peptide") |>
  select(`Subject level ID or Number (SUBJID)`,
         `Visit Name (VISIT)`,
         `Accession ID or Number (ACCSNNUM)`,
         `Specimen ID or Number (SPECNUM)`,
         `lab date (lbdt)`,
         `lab time (lbtm)`,
         `Received Date (RCVDTM)`,
         `Specimen Condition (SPECCND)`,
         `Lab - Specimen Comments (SPECCOM)`,
         `Specimen Material Name (LBSPEC)`,
         `Lab Test Name (LBTEST)`,
         `Test Name ID (TSTNAM)`,
         `Additional Test Description (TSTDESC)`,
         `Reported Numeric Result (RPTRESN)`,
         `Reported Units (RPTU)`,
         `lab date`)
# head(PPD_lb_tnsf_cpeptide)
```

```{r All cpeptide around the OGTT test ,include=FALSE}
all_dat_cpep <- OGTT_times |> # filtering cpeptide data to OGTT collection times 
  left_join(PPD_lb_tnsf_cpeptide, by=c("Subject Identifier (SUBNUM)"="Subject level ID or Number (SUBJID)",
                                       "OGTT Procedure Date: (AGSTDAT)"="lab date")
  ) |>
  mutate(`OGTT datetime` = ymd_hms(paste0(as.character(`OGTT Procedure Date: (AGSTDAT)`)," ",`Glucose Consumption Start Time: (AGSTTIM)`)),
         `Lab datetime` = ymd_hm(paste0(as.character(`lab date (lbdt)`)," ",`lab time (lbtm)`)),
         `Lab time rel OGTT` = difftime(`Lab datetime`,  `OGTT datetime`, units = "mins"),
         `pre-post OGTT` = ifelse(`Lab time rel OGTT`<=0,
                                  "Pre OGTT start",
                                  "Post OGTT start"),
         `Visit label` = factor(Visit,
                                levels = c("Day -1", "Day 7", "Day 14", "Day 21", "Day 28", "Week 8", 
                                           "Week 12", "Week 16", "Week 20", "Week 26", "Unscheduled")
         )
  ) |>
  relocate(c(`OGTT datetime`, `pre-post OGTT`), .after = `Visit Name (VISIT)`) |>
  filter(!is.na(`Reported Numeric Result (RPTRESN)`)) |>
  arrange(`Subject Identifier (SUBNUM)`,
          `Visit label`,
          `Additional Test Description (TSTDESC)`) |>
  filter(!`Additional Test Description (TSTDESC)` %in% c("OGTT C Peptide 10hr","OGTT C Peptide 6hr",
                                                         "C Peptide","C Peptide 6hr","C Peptide 8hr","C Peptide 10hr"))
head(all_dat_cpep)
colnames(all_dat_cpep)
```

```{r Begin glucose work filter PPD CL to glucose , include=FALSE}
PPD_lb_tnsf_glucose <- PPD_lb_tnsf_gluc_insulin |> # names(PPD_lb_tnsf_gluc_insulin)
  filter(`Lab Test Name (LBTEST)` %in% c("Glucose", "Glucose, Random")) |>
  filter(!`Additional Test Description (TSTDESC)` == "Chemistry") |>
  select(`Subject level ID or Number (SUBJID)`,
         `Visit Name (VISIT)`,
         `Accession ID or Number (ACCSNNUM)`,
         `Specimen ID or Number (SPECNUM)`,
         `lab date (lbdt)`,
         `lab time (lbtm)`,
         `Received Date (RCVDTM)`,
         `Specimen Condition (SPECCND)`,
         `Lab - Specimen Comments (SPECCOM)`,
         `Specimen Material Name (LBSPEC)`,
         `Lab Test Name (LBTEST)`,
         `Test Name ID (TSTNAM)`,
         `Additional Test Description (TSTDESC)`,
         `Reported Numeric Result (RPTRESN)`,
         `Reported Units (RPTU)`,
         `lab date`)
head(PPD_lb_tnsf_glucose)
```

```{r All cpeptide around the OGTT test, include=FALSE}
all_dat_gluc <- OGTT_times |> # filtering cpeptide data to OGTT collection times 
  left_join(PPD_lb_tnsf_glucose, by=c("Subject Identifier (SUBNUM)"="Subject level ID or Number (SUBJID)",
                                       "OGTT Procedure Date: (AGSTDAT)"="lab date")
  ) |>
  mutate(`OGTT datetime` = ymd_hms(paste0(as.character(`OGTT Procedure Date: (AGSTDAT)`)," ",`Glucose Consumption Start Time: (AGSTTIM)`)),
         `Lab datetime` = ymd_hm(paste0(as.character(`lab date (lbdt)`)," ",`lab time (lbtm)`)),
         `Lab time rel OGTT` = difftime(`Lab datetime`,  `OGTT datetime`, units = "mins"),
         `pre-post OGTT` = ifelse(`Lab time rel OGTT`<=0,
                                  "Pre OGTT start",
                                  "Post OGTT start"),
         `Visit label` = factor(ifelse(str_detect(`Visit`, "MAD2"),
                                       "Day 14",
                                       `Visit`),
                                levels = c("Day -1", "Day 7", "Day 14", "Day 21", "Day 28",  "Week 8", 
                                           "Week 12", "Week 16", "Week 20", "Week 26")
         )
  ) |>
  relocate(c(`OGTT datetime`, `pre-post OGTT`), .after = `Visit Name (VISIT)`) |>
  filter(!is.na(`Reported Numeric Result (RPTRESN)`)) |>
  arrange(`Subject Identifier (SUBNUM)`,
          `Visit label`,
          `Additional Test Description (TSTDESC)`) |>
  filter(!`Additional Test Description (TSTDESC)` %in% c("Plasma Glucose 6hr","Plasma Glucose 8hr","Plasma Glucose 10hr",
                                                         "Plasma Glucose 12hr","Plasma Glucose 14hr","Plasma Glucose 16hr","Plasma Glucose 26hr",
                                                         "OGTT Plasma Glucose 6hr","OGTT Plasma Glucose 10hr","C Peptide 8hr","C Peptide 10hr")) 
head(all_dat_gluc)
colnames(all_dat_gluc)
```

# Cpeptide data

```{r include=FALSE}
data_cpep = data.frame(
subject = all_dat_cpep$`Subject Identifier (SUBNUM)`,
visit = all_dat_cpep$Visit,
time = all_dat_cpep$`Additional Test Description (TSTDESC)`,
treatment = all_dat_cpep$`pre-post OGTT`,
followup = all_dat_cpep$`Lab time rel OGTT`,
result = all_dat_cpep$`Reported Numeric Result (RPTRESN)`
)
head(data_cpep)
table(data_cpep$visit)
table(data_cpep$time)
table(data_cpep$followup)
```

```{r sorting C-Peptide data for Imputation}
data_cpep$time = case_when(
  data_cpep$time == "C Peptide 2hr" ~ "OGTT C Peptide 0 Min",
  data_cpep$time == "C Peptide 2.5hr" ~ "OGTT C Peptide 30 Min",
  data_cpep$time == "C Peptide 3hr" ~ "OGTT C Peptide 1hr",
  data_cpep$time == "C Peptide 3.5hr" ~ "OGTT C Peptide 1.5hr",
  data_cpep$time == "C Peptide 4hr" ~ "OGTT C Peptide 2hr",
  TRUE ~ data_cpep$time
)
data_cpep = data_cpep |>
  filter(time %in% c("OGTT C Peptide 0 Min", "OGTT C Peptide 30 Min", "OGTT C Peptide 1hr", "OGTT C Peptide 1.5hr", "OGTT C Peptide 2hr")) |>
  filter(!visit %in% c("Day 7", "Day 21", "Unscheduled"))
data_cpep$time = case_when(
  data_cpep$time == "OGTT C Peptide 0 Min" ~ "0hr",
  data_cpep$time == "OGTT C Peptide 30 Min" ~ "0.5hr",
  data_cpep$time == "OGTT C Peptide 1hr" ~ "1hr",
  data_cpep$time == "OGTT C Peptide 1.5hr" ~ "1.5hr",
  data_cpep$time == "OGTT C Peptide 2hr" ~ "2hr",
  TRUE ~ data_cpep$time
)
data_cpep$visit =  case_when(
  data_cpep$visit == "Day -1" ~ "0",
  data_cpep$visit == "Day 14" ~ "2",
  data_cpep$visit == "Day 28" ~ "4",
  data_cpep$visit == "Week 8" ~ "8",
  data_cpep$visit == "Week 12" ~ "12",
  data_cpep$visit == "Week 16" ~ "16",
  data_cpep$visit == "Week 20" ~ "20",
  data_cpep$visit == "Week 26" ~ "26",
  TRUE ~ data_cpep$visit
)
table(data_cpep$time,data_cpep$treatment,data_cpep$visit)
table(data_cpep$time)
```

```{r Plots Cpeptide data}
cpep_time = ggplot(data_cpep, aes(x = result, y = time)) + geom_point() +theme_classic()
cpep_visit = ggplot(data_cpep, aes(y = visit, x = result)) + geom_point() +theme_classic()
```

# Glucose data

```{r include=FALSE}
data_gluc = data.frame(
subject = all_dat_gluc$`Subject Identifier (SUBNUM)`,
visit = all_dat_gluc$Visit,
time = all_dat_gluc$`Additional Test Description (TSTDESC)`,
treatment = all_dat_gluc$`pre-post OGTT`,
followup = all_dat_gluc$`Lab time rel OGTT`,
result = all_dat_gluc$`Reported Numeric Result (RPTRESN)`)
head(data_gluc)
table(data_gluc$visit)
table(data_gluc$time)
```

```{r sorting Glucose Data for Imputation}
data_gluc$time = case_when(
  data_gluc$time == "Plasma Glucose 2hr" ~ "OGTT Plasma Glucose 0 Min",
  data_gluc$time == "Plasma Glucose 2.5hr" ~ "OGTT Plasma Glucose 30 Min",
  data_gluc$time == "Plasma Glucose 3hr" ~ "OGTT Plasma Glucose 1hr",
  data_gluc$time == "Plasma Glucose 3.5hr" ~ "OGTT Plasma Glucose 1.5hr",
  data_gluc$time == "Plasma Glucose 4hr" ~ "OGTT Plasma Glucose 2hr",
  TRUE ~ data_gluc$time
)
data_gluc = data_gluc |>
  filter(time %in% c("OGTT Plasma Glucose 0 Min", "OGTT Plasma Glucose 30 Min", "OGTT Plasma Glucose 1hr", "OGTT Plasma Glucose 1.5hr", "OGTT Plasma Glucose 2hr"))|>
  filter(!visit %in% c("Day 7", "Day 21", "Unscheduled"))

data_gluc$time = case_when(
  data_gluc$time == "OGTT Plasma Glucose 0 Min"~ "0hr",
  data_gluc$time == "OGTT Plasma Glucose 30 Min" ~ "0.5hr",
  data_gluc$time == "OGTT Plasma Glucose 1hr" ~ "1hr",
  data_gluc$time == "OGTT Plasma Glucose 1.5hr" ~ "1.5hr",
  data_gluc$time == "OGTT Plasma Glucose 2hr" ~ "2hr",
  TRUE ~ data_gluc$time
)
data_gluc$visit =  case_when(
  data_gluc$visit == "Day -1" ~ "0",
  data_gluc$visit == "Day 14" ~ "2",
  data_gluc$visit == "Day 28" ~ "4",
  data_gluc$visit == "Week 8" ~ "8",
  data_gluc$visit == "Week 12" ~ "12",
  data_gluc$visit == "Week 16" ~ "16",
  data_gluc$visit == "Week 20" ~ "20",
  data_gluc$visit == "Week 26" ~ "26",
  TRUE ~ data_gluc$visit
)
table(data_gluc$visit)
table(data_gluc$time)
```


```{r  Plots Glucose data ,include=FALSE}
gluc_time = ggplot(data_gluc, aes(x = result, y = time)) + geom_point() + theme_classic()
gluc_visit = ggplot(data_gluc, aes(x = result,y  = visit)) + geom_point()  + theme_classic()
```

# Plots Cpeptide and Glucose

```{r eval=FALSE, include=FALSE}
grid.arrange(cpep_visit, gluc_visit,cpep_time,gluc_time, ncol = 2)
ggplot(data_cpep, aes(x = time, y = result , color = visit )) + geom_point(size = 1) +theme_classic()+ ggtitle("C-Peptide")
```

# Cpeptide Interaction plot

```{r echo=FALSE, warning=FALSE}
data_cpep$time = factor(data_cpep$time, levels = c("0hr", "0.5hr", "1hr", "1.5hr", "2hr"))
data_cpep$visit = factor(data_cpep$visit, levels = c("0", "2", "4", "8", "12", "16", "20", "26"))
grid.arrange(
  ggplot(data_cpep, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Median Response",
       color = "Visit")+
  theme_classic()
,
ggplot(data_cpep, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Week",
       y = "Mean Response",
       color = "Time") +
  theme_classic()
,
ggplot(data_cpep, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Visit") +
  theme_classic()
,
ggplot(data_cpep, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Week",
       y = "Mean Response",
       color = "Time") +
  theme_classic()
,nrow = 2)
```

```{r Imputation for c-peptide, message=FALSE, warning=FALSE, include=FALSE}
# Create a complete grid of factor combinations
all_combinations <- expand.grid(
  visit = unique(data_cpep$visit),
  time = unique(data_cpep$time),
  subject = unique(data_cpep$subject)
)
# Merge to ensure all combinations are present
data_cpep <- left_join(all_combinations, data_cpep, by = c("visit", "time","subject"))
write.csv(data_cpep, "data/data_cpep.csv")
data_cpep <- read_csv("data/data_cpep.csv")
# Perform multiple imputation
data_complete_cpep=complete(mice(data_cpep, m = 50, method = 'pmm', seed = 123))
dim(data_complete_cpep)
write.csv(data_complete_cpep, "data/data_cpep_mice.csv")
data_gluc <- read_csv("data/data_cpep_mice.csv")
```

# cpepetide interaction plot complete data

```{r echo=FALSE}
data_complete_cpep$time = factor(data_complete_cpep$time, levels = c("0hr", "0.5hr", "1hr", "1.5hr", "2hr"))
data_complete_cpep$visit = factor(data_complete_cpep$visit, levels = c("0", "2", "4", "8", "12", "16", "20", "26"))
grid.arrange(
  ggplot(data_complete_cpep, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Median Response",
       color = "Visit")+
  theme_classic()
,
ggplot(data_complete_cpep, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Week",
       y = "Mean Response",
       color = "Time") +
  theme_classic()
,
ggplot(data_complete_cpep, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Visit") +
  theme_classic()
,
ggplot(data_complete_cpep, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Week",
       y = "Mean Response",
       color = "Time") +
  theme_classic()
,nrow = 2)
```


# Glucose Interaction plot

```{r}
data_gluc$time = factor(data_gluc$time, levels = c("0hr", "0.5hr", "1hr", "1.5hr", "2hr"))
data_gluc$visit = factor(data_gluc$visit, levels = c("0", "2", "4", "8", "12", "16", "20", "26"))
grid.arrange(
  ggplot(data_gluc, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Median Response",
       color = "Week")+
  theme_classic()
,
ggplot(data_gluc, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Visit",
       y = "Median Response",
       color = "Time") +
  theme_classic()
,
ggplot(data_gluc, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Week") +
  theme_classic()
,
ggplot(data_gluc, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Visit",
       y = "Mean Response",
       color = "Time") +
  theme_classic()

,nrow = 2)
```


```{r Glucose Imputation, message=FALSE, warning=FALSE, include=FALSE}
# Create a complete grid of factor combinations
all_combinations <- expand.grid(
  subject = unique(data_gluc$subject),
  visit = unique(data_gluc$visit),
  time = unique(data_gluc$time)
)
# Merge to ensure all combinations are present
data_gluc <- left_join(all_combinations, data_gluc, by = c("visit", "time","subject"))
write.csv(data_gluc, "data/data_gluc.csv")
data_gluc <- read_csv("data/data_gluc.csv")
# Perform multiple imputation
data_complete_gluc=complete(mice(data_gluc,m=50, method = 'pmm', seed = 123))
dim(data_complete_gluc)
write.csv(data_complete_gluc, "data/data_gluc_mice.csv")
data_gluc <- read_csv("data/data_gluc_mice.csv")
```

# Glucose interaction plot complete data

```{r echo=FALSE}
data_complete_gluc$time = factor(data_complete_gluc$time, levels = c("0hr", "0.5hr", "1hr", "1.5hr", "2hr"))
data_complete_gluc$visit = factor(data_complete_gluc$visit, levels = c("0", "2", "4", "8", "12", "16", "20", "26"))
grid.arrange(
  ggplot(data_complete_gluc, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Median Response",
       color = "Visit")+
  theme_classic()
,
ggplot(data_complete_gluc, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = median, geom = "line", size = 0.5) +
  stat_summary(fun = median, geom = "point", size = 1.5) +
  labs(x = "Week",
       y = "Mean Response",
       color = "Time") +
  theme_classic()
,
ggplot(data_complete_gluc, aes(x = time, y = result, color = visit, group = visit)) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Time",
       y = "Mean Response",
       color = "Visit") +
  theme_classic()
,
ggplot(data_complete_gluc, aes(x = visit, y = result, color = time, group =time )) +
  stat_summary(fun = mean, geom = "line", size = 0.5) +
  stat_summary(fun = mean, geom = "point", size = 1.5) +
  labs(x = "Week",
       y = "Mean Response",
       color = "Time") +
  theme_classic()
,nrow = 2)
```




